### PR TITLE
Add `openssl_fips` variable to gyp bindings

### PR DESCRIPTION
**Pull request by cswendrowski**
See https://github.com/Level/classic-level/pull/71#issuecomment-1476741633.

### CODE REVIEW

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
Merging so that I can run the [smoke](https://github.com/Level/classic-level/blob/89397fd0cedf5637ffac866f7e2c7505ddcdbfde/.github/workflows/smoke.yml) workflow. If that succeeds I'll do a release tomorrow.

**Comment by vweevers** [comment]
It's been a long day; postponing.

**Comment by cswendrowski** [comment]
> It's been a long day; postponing.

Just wanted to nudge here - we are doing a release at the end of next week, do you think a release with these changes can be made by then?

**Comment by vweevers** [comment]
Yes, I have some days off next week and will get this out the door.

**Comment by vweevers** [comment]
[1.3.0](https://github.com/Level/classic-level/releases/tag/v1.3.0)

**Pull request merged**
