### PR TITLE
Breaking: bump `abstract-level` to 2.0.0

### PR DESCRIPTION
**Pull request by vweevers**
TODO:

- [x] Pass abstract test suite
- [x] Update additional tests
- [x] Update types
- [x] Cleanup the closing of iterators (see TODO comments in binding)
- [x] Update docs
- [x] Write upgrade guide
- [x] Create snapshot for `get()` synchronously (https://github.com/Level/community/issues/118)
- [x] Support `signal` option on iterators
- [ ] Benchmark (optional):
  - [ ] `get()` concurrently, to see if synchronous snapshot blocks event loop
  - [ ] `iterator()`, to compare callbacks vs promises
  - [ ] `put()`, to compare callbacks vs promises

To be rebased (not fully squashed) before merge.

### CODE REVIEW

**Comment by ishfx** [comment]
Hey, when do you plan to merge v2? Looking forward to it, thanks!

**Comment by jacoscaz** [comment]
@vweevers would you like some help with benchmarking?

**Comment by vweevers** [comment]
Help is always welcome, thank you! Though FYI, that's not why I haven't released this yet. Just haven't had the time, and I don't consider benchmarks to be a blocker (because e.g. promises are unlikely to make a big difference here) so I planned to just skip them when I got to it.

The only thing that slightly worries me is that `db.get()` now creates a snapshot synchronously. I don't know if that's a fast operation for LevelDB.

**Comment by jacoscaz** [comment]
@vweevers no pressure meant or implied. I depend on level packages through [quadstore](https://github.com/jacoscaz/quadstore) and I'd be happy to help an upstream dependency if I can find the time.

Also, my experience with promise-based iteration is exactly the opposite; so far I've always found it to make a rather big difference, particularly with asynchronous sources capable of reading and returning multiple items in batches and particularly when structuring chains of iterators. That said, I also recognize that I'm not as experienced as you are. I'll have a look next week!

**Comment by vweevers** [comment]
I'm not that experienced with promises themselves, I meant more that disk and the C<>JS barrier are the bigger bottlenecks here. But it's always good to challenge such assumptions. You're probably right that there's an overhead to e.g. async iterators.

For people that were already using promises, I do hope that abstract-level v2 and classic-level v2 are faster because they no longer have to translate callbacks into promises, allowing V8 to optimize it.

**Comment by vweevers** [comment]
> To be rebased (not fully squashed) before merge.

Done. I squashed some commits, tweaked descriptions. This push contains no code changes besides a typo and changing `bool aborted_` to `std::atomic<bool> aborted_`.

Considering the amount of time passed since I opened this PR, I want to revisit CI, e.g. to drop Node.js 16 and bump the `electron` version we test against. I'll do that in a separate PR.

**Comment by vweevers** [comment]
Canceling CI because macos jobs are stuck in the queue for 10+ minutes.

**Comment by vweevers** [comment]
[2.0.0](https://github.com/Level/classic-level/releases/tag/v2.0.0)

**Pull request merged**
