### PR TITLE
Update CI and dev dependencies

### PR DESCRIPTION
**Pull request by vweevers**

### CODE REVIEW

**Comment by vweevers** [comment]
Also running smoke to test prebuilds: https://github.com/Level/classic-level/actions/runs/11427969380

**Comment by cclauss** [comment]
Perhaps add `fail-fast` to see which tests are really failing.
* https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

**Comment by vweevers** [comment]
> Perhaps add `fail-fast: false`

Yeah, I sometimes add that in temporarily, but normally I prefer the default behavior, to not have to cancel manually. Thanks for the suggestion.

**Review by cclauss — APPROVED** [review]

**Comment by vweevers** [comment]
Smoke [fails](https://github.com/Level/classic-level/actions/runs/11428128189/job/31793042743) on win32-x86 with:

```
gyp http 500 https://nodejs.org/dist/v23.0.0/win-x86/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500 status code downloading ia32 node.lib
gyp ERR! stack at downloadNodeLib (D:\a\classic-level\classic-level\node_modules\node-gyp\lib\install.js:334:15)
```

Turns out Node.js 23 removed support of 32-bit Windows (https://github.com/nodejs/node/pull/53184) so I'll restore the `--target` argument in order to build against 18.

**Comment by vweevers** [comment]
That's fixed. Next issue is that linux-x64 [fails](https://github.com/Level/classic-level/actions/runs/11428345151) with:

```
Traceback (most recent call last):
  File "/input/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
  File "/input/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/input/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module>
    import gyp.common
  File "/input/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435
    if CC := os.environ.get("CC_target") or os.environ.get("CC"):
           ^
SyntaxError: invalid syntax
```

It's using Python 3.6.8. Need to update (or maybe just rebuild) https://github.com/prebuild/docker-images/blob/master/centos7-devtoolset7/Dockerfile.

**Review by juliangruber — APPROVED** [review]

**Comment by vweevers** [comment]
That's fixed as well. Smoke now passes, meaning we're ready to release v2 🙂

**Pull request merged**
